name: Release

permissions:
  contents: write

on: [push]

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: nightly
            os: ubuntu-24.04
          - toolchain: nightly-2024-01-01
            os: ubuntu-24.04
          - toolchain: stable
            os: ubuntu-24.04
          - toolchain: stable-2024-01-01
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy
          rustflags: "-A warnings"
          toolchain: ${{ matrix.toolchain }}

      - name: run
        run: |
          rustc -Vv
          cargo run -q
